---
title: "Covid19 Carcel"
author: "Daniel Quinteros"
date: "30/6/2020"
output: html_document
---


```{r, include=FALSE}
library(hrbrthemes)
library(dplyr)
library(ggrepel)
library(ggplot2)
library(smoother)
library(HDInterval)
library(tidyverse)

covid.carcel <- read.csv(url("https://raw.githubusercontent.com/danielquinterosr/master/covid_carcel_chile/covid.carcel.csv"), header=TRUE, sep=";")
covid.carcel$fecha <- as.Date(covid.carcel$fecha, "%d-%m-%y")
covid.carcel$contagio.ppl <- as.numeric(covid.carcel$contagio.ppl)
covid.carcel$contagio.fx <- as.numeric(covid.carcel$contagio.fx)
covid.carcel$muerte.ppl <- as.numeric(covid.carcel$muerte.ppl)
covid.carcel$muerte.fx <- as.numeric(covid.carcel$muerte.fx)
covid.carcel$recupera.ppl <- as.numeric(covid.carcel$recupera.ppl)
covid.carcel$recupera.fx <- as.numeric(covid.carcel$recupera.fx)
str(covid.carcel)

contagio <- subset(covid.carcel, select = c(contagio.fx,contagio.ppl,fecha))
colnames(contagio)[which(names(contagio) == "contagio.ppl")] <- "Priv. libertad"
colnames(contagio)[which(names(contagio) == "contagio.fx")] <- "Funcionario/a"
contagio.largo <- reshape2::melt(contagio, id.var='fecha')

```

## 1. Evolución del Covid-19 en las cárceles de Chile

*Fuente: Gendarmería de Chile (gendarmeria.gob.cl/corona_2020.html)*
```{r, echo=FALSE}
graf.contagio <- ggplot(contagio.largo, aes(x=fecha, y=value, col=variable)) +
geom_line(size=1.1, alpha=0.7, linetype=1) +
geom_text_repel(data=subset(contagio.largo, fecha=="2020-04-15" | fecha=="2020-04-30" | fecha=="2020-05-15" | fecha=="2020-05-31" | fecha=="2020-06-15" | fecha=="2020-06-30"), aes(y=value,label=value),size=4, fontface="bold", position="identity",show_guide=FALSE) +
xlab("") + ylab("") +
scale_x_date(date_breaks = "1 week", date_labels = "%d-%m") +
theme_ipsum() +
ggtitle("Contagio Covid-19 en Cárceles de Chile (30jun2020)") +
theme(legend.position="top", legend.title = element_blank(),legend.text = element_text(size=7))
print(graf.contagio)
```


## 2. R_efectivo: el número de reproducción efectiva en las cárceles de Chile

*Fuente: https://www.datacamp.com/community/tutorials/replicating-in-r-covid19*

### 2.1 Nuevos casos por día (población penal)
```{r, echo=FALSE}

# r_t_range is a vector of possible values for R_t
R_T_MAX = 12
r_t_range = seq(0, R_T_MAX, length = R_T_MAX*100 + 1)

# Gamma is 1/serial interval
# https://wwwnc.cdc.gov/eid/article/26/6/20-0357_article
GAMMA = 1/4

# Utility functions

## We will use a utility function to display the head of dataframes.
## Note that we need this hack mainly to add the class 'dataframe' to
## the tables that are printed. This should ideally be handled
## by the `repr` package, and I will be sending a PR.
display_df <- function(x){
  d <- as.character(
    knitr::kable(x, format = 'html', table.attr = "class='dataframe'")
  )
  IRdisplay::display_html(d)
}

display_head <- function(x, n = 6){
   display_df(head(x, n))
}

display_random <- function(x, n = 6){
   display_df(dplyr::sample_n(x, n))
}

#' Compute new cases and smooth them
smooth_new_cases <- function(cases){
  cases %>%
    arrange(date) %>%
    mutate(new_cases = c(cases[1], diff(cases))) %>%
    mutate(new_cases_smooth = round(
      smoother::smth(new_cases, window = 7, tails = TRUE)
    )) %>%
    select(date, cases, new_cases, new_cases_smooth)
}

covid_cases <- subset(covid.carcel, select = c(contagio.ppl,fecha))
colnames(covid_cases)[which(names(covid_cases) == "contagio.ppl")] <- "cases"
colnames(covid_cases)[which(names(covid_cases) == "fecha")] <- "date"

covid_cases %>%
  smooth_new_cases()


plot_new_cases <- function(cases){
  cases %>%
    ggplot(aes(x = date, y = new_cases)) +
    geom_line(linetype = 'dotted', color = 'gray40') +
    geom_line(aes(y = new_cases_smooth), color = "#14243e") +
    labs(
      title = "Casos nuevos por día (internos/as)",
      subtitle = unique(cases$state),
      x = NULL, y = NULL
    )
}

covid_cases %>%
  smooth_new_cases() %>%
  plot_new_cases()

```

### 2.2 R_efectivo de población penal
```{r, echo=FALSE}

compute_likelihood <- function(cases){
  likelihood <- cases %>%
    filter(new_cases_smooth > 0) %>%
    mutate(
      r_t = list(r_t_range),
      lambda = map(lag(new_cases_smooth, 1), ~ .x * exp(GAMMA * (r_t_range - 1))),
      likelihood_r_t = map2(new_cases_smooth, lambda, dpois, log = TRUE)
    ) %>%
    slice(-1) %>%
    select(-lambda) %>%
    unnest(c(likelihood_r_t, r_t))
}

covid_cases %>%
  smooth_new_cases() %>%
  compute_likelihood()
```


```{r, echo=FALSE}

compute_posterior <- function(likelihood){
  likelihood %>%
    arrange(date) %>%
    group_by(r_t) %>%
    mutate(posterior = exp(
      zoo::rollapplyr(likelihood_r_t, 7, sum, partial = TRUE)
    )) %>%
    group_by(date) %>%
    mutate(posterior = posterior / sum(posterior, na.rm = TRUE)) %>%
    # HACK: NaNs in the posterior create issues later on. So we remove them.
    mutate(posterior = ifelse(is.nan(posterior), 0, posterior)) %>%
    ungroup() %>%
    select(-likelihood_r_t)
}

covid_cases %>%
  smooth_new_cases() %>%
  compute_likelihood() %>%
  compute_posterior()
```


```{r, echo=FALSE}

plot_posteriors <- function(posteriors){
  posteriors %>%
    ggplot(aes(x = r_t, y = posterior, group = date)) +
    geom_line(alpha = 0.2) +
    labs(
      title = expression(paste("Daily Posterior of R"[t], " by day")),
      subtitle = unique(posteriors$state),
      x = '',
      y = ''
    ) +
    coord_cartesian(xlim = c(0.4, 4)) +
    theme(legend.position = 'none')
}

covid_cases %>%
  smooth_new_cases() %>%
  compute_likelihood() %>%
  compute_posterior() %>%
  plot_posteriors()
```

```{r, echo=FALSE}

estimate_rt <- function(posteriors){
  posteriors %>%
    group_by(date) %>%
    summarize(
      r_t_simulated = list(sample(r_t_range, 10000, replace = TRUE, prob = posterior)),
      r_t_most_likely = r_t_range[which.max(posterior)]
    ) %>%
    mutate(
      r_t_lo = map_dbl(r_t_simulated, ~ hdi(.x)[1]),
      r_t_hi = map_dbl(r_t_simulated, ~ hdi(.x)[2])
    ) %>%
    select(-r_t_simulated)
}

covid_cases %>%
  smooth_new_cases() %>%
  compute_likelihood() %>%
  compute_posterior() %>%
  estimate_rt()
```

```{r, echo=FALSE}

plot_estimates <- function(estimates){
  estimates %>%
    ggplot(aes(x = date, y = r_t_most_likely)) +
    geom_point(color = "darkorange", alpha = 0.8, size = 4) +
    geom_line(color = "#14243e") +
    geom_hline(yintercept = 1, linetype = 'dashed') +
    geom_ribbon(
      aes(ymin = r_t_lo, ymax = r_t_hi),
      fill = 'darkred',
      alpha = 0.2
    ) +
    labs(
      title = expression('Reproducción efectiva (internos/as) R'[e]), x = '', y = '',
      subtitle = unique(estimates$state)
    ) +
    coord_cartesian(ylim = c(0, 4))
}

covid_cases %>%
  smooth_new_cases() %>%
  compute_likelihood() %>%
  compute_posterior() %>%
  estimate_rt() %>%
  plot_estimates()
```

### 2.3. Nuevos casos por día (Funcionarios/as)

```{r, echo=FALSE}

covid_genchi <- subset(covid.carcel, select = c(contagio.fx,fecha))
colnames(covid_genchi)[which(names(covid_genchi) == "contagio.fx")] <- "cases"
colnames(covid_genchi)[which(names(covid_genchi) == "fecha")] <- "date"

plot_new_cases <- function(cases){
  cases %>%
    ggplot(aes(x = date, y = new_cases)) +
    geom_line(linetype = 'dotted', color = 'gray40') +
    geom_line(aes(y = new_cases_smooth), color = "#14243e") +
    labs(
      title = "Casos nuevos por día (funcionario/as)",
      subtitle = unique(cases$state),
      x = NULL, y = NULL
    )
}

covid_genchi %>%
  smooth_new_cases() %>%
  plot_new_cases()
```

### 2.4 R_efectivo de funcionarios/as GENCHI
```{r, echo=FALSE}

covid_genchi %>%
  smooth_new_cases() %>%
  compute_likelihood() %>%
  compute_posterior() %>%
  plot_posteriors()
```


```{r, echo=FALSE}

plot_estimates <- function(estimates){
  estimates %>%
    ggplot(aes(x = date, y = r_t_most_likely)) +
    geom_point(color = "green", alpha = 0.8, size = 4) +
    geom_line(color = "#14243e") +
    geom_hline(yintercept = 1, linetype = 'dashed') +
    geom_ribbon(
      aes(ymin = r_t_lo, ymax = r_t_hi),
      fill = 'darkgreen',
      alpha = 0.2
    ) +
    labs(
      title = expression('Reproducción efectiva (funcionarios/as) R'[e]), x = '', y = '',
      subtitle = unique(estimates$state)
    ) +
    coord_cartesian(ylim = c(0, 4))
}

covid_genchi %>%
  smooth_new_cases() %>%
  compute_likelihood() %>%
  compute_posterior() %>%
  estimate_rt()

covid_genchi %>%
  smooth_new_cases() %>%
  compute_likelihood() %>%
  compute_posterior() %>%
  estimate_rt() %>%
  plot_estimates()
```




